In [3]:
!pip install pandas
# or pip install pandas in cmd

Collecting pandas
  Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.2-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\disha\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\disha\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\disha\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 428.4 kB/s eta 0:00:22
   -- ------------------------------------- 0.5/9.9 MB 428.4 kB/s eta 0:00:22
   -- ------------------------------------- 0.5/9.9 MB 428.4 kB/s eta 0:00:22
   --- ------------------------------------ 0.8/9.9 MB 463.7 kB/s eta 0:00:20
   --- ------------------------------------ 0.8/9.9 MB 463.7 kB/s eta 0:00:20
   ---- ----------------------------------- 1.0/9.9 MB 460.9 kB/s eta 0:00:20
   ---- ----------------------------------- 1.0/9.9 MB 460.9 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.9 MB 498.5 kB/s eta 0:00:18
   ------ --------------------------------- 1.6/9.9 MB 572.9 kB/s eta 0:00:15
   ------- -------------------------------- 1.8/9.9 MB 627.6 kB/s eta 0:00:13
   -------- ------------------------------- 2.1/9.9 MB 683.1 kB/s eta 0:00:12
   --------- ------------------------------ 2.4/9.9 MB 738.2 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/9.9 MB 773.4 kB/s eta 0:00:10
   ----------- ---------------------------- 2.9/9.9 MB 803.6 kB/s eta 0:00:09
   ----------- ---------------------------- 2.9/9.9 MB 803.6 kB/s eta 0:00:09
   ------------ --------------------------- 3.1/9.9 MB 804.1 kB/s eta 0:00:09
   ------------- -------------------------- 3.4/9.9 MB 794.2 kB/s eta 0:00:09
   ------------- -------------------------- 3.4/9.9 MB 794.2 kB/s eta 0:00:09
   -------------- ------------------------- 3.7/9.9 MB 801.6 kB/s eta 0:00:08
   -------------- ------------------------- 3.7/9.9 MB 801.6 kB/s eta 0:00:08
   --------------- ------------------------ 3.9/9.9 MB 763.4 kB/s eta 0:00:08
   --------------- ------------------------ 3.9/9.9 MB 763.4 kB/s eta 0:00:08
   --------------- ------------------------ 3.9/9.9 MB 763.4 kB/s eta 0:00:08
   ----------------- ---------------------- 4.2/9.9 MB 729.6 kB/s eta 0:00:08
   ----------------- ---------------------- 4.2/9.9 MB 729.6 kB/s eta 0:00:08
   ----------------- ---------------------- 4.2/9.9 MB 729.6 kB/s eta 0:00:08
   ------------------ --------------------- 4.5/9.9 MB 713.5 kB/s eta 0:00:08
   ------------------ --------------------- 4.5/9.9 MB 713.5 kB/s eta 0:00:08
   ------------------- -------------------- 4.7/9.9 MB 690.6 kB/s eta 0:00:08
   ------------------- -------------------- 4.7/9.9 MB 690.6 kB/s eta 0:00:08
   ------------------- -------------------- 4.7/9.9 MB 690.6 kB/s eta 0:00:08
   ------------------- -------------------- 4.7/9.9 MB 690.6 kB/s eta 0:00:08
   -------------------- ------------------- 5.0/9.9 MB 648.2 kB/s eta 0:00:08
   -------------------- ------------------- 5.0/9.9 MB 648.2 kB/s eta 0:00:08
   -------------------- ------------------- 5.0/9.9 MB 648.2 kB/s eta 0:00:08
   --------------------- ------------------ 5.2/9.9 MB 643.0 kB/s eta 0:00:08
   --------------------- ------------------ 5.2/9.9 MB 643.0 kB/s eta 0:00:08
   ---------------------- ----------------- 5.5/9.9 MB 632.5 kB/s eta 0:00:07
   ---------------------- ----------------- 5.5/9.9 MB 632.5 kB/s eta 0:00:07
   ---------------------- ----------------- 5.5/9.9 MB 632.5 kB/s eta 0:00:07
   ----------------------- ---------------- 5.8/9.9 MB 624.5 kB/s eta 0:00:07
   ----------------------- ---------------- 5.8/9.9 MB 624.5 kB/s eta 0:00:07
   ----------------------- ---------------- 5.8/9.9 MB 624.5 kB/s eta 0:00:07
   ------------------------ --------------- 6.0/9.9 MB 610.0 kB/s eta 0:00:07
   ------------------------ --------------- 6.0/9.9 MB 610.0 kB/s eta 0:00:07
   ------------------------ --------------- 6.0/9.9 MB 610.0 kB/s eta 0:00:07
   ------------------------- -------------- 6.3/9.9 MB 602.7 kB/s eta 0:00:06
   ------------------------- -------------- 6.3/9.9 MB 602.7 kB/s eta 0:00:06
   -------------------------- ------------- 6.6/9.9 MB 597.6 kB/s eta 0:00:06
   -------------------------- ------------- 6.6/9.9 MB 597.6 kB/s eta 0:00:06
   -------------------------- ------------- 6.6/9.9 MB 597.6 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/9.9 MB 592.1 kB/s eta 0:00:06
   --------------------------- ------------ 6.8/9.9 MB 592.1 kB/s eta 0:00:06
   ---------------------------- ----------- 7.1/9.9 MB 583.3 kB/s eta 0:00:05
   ---------------------------- ----------- 7.1/9.9 MB 583.3 kB/s eta 0:00:05
   ---------------------------- ----------- 7.1/9.9 MB 583.3 kB/s eta 0:00:05
   ----------------------------- ---------- 7.3/9.9 MB 578.4 kB/s eta 0:00:05
   ----------------------------- ---------- 7.3/9.9 MB 578.4 kB/s eta 0:00:05
   ----------------------------- ---------- 7.3/9.9 MB 578.4 kB/s eta 0:00:05
   ------------------------------ --------- 7.6/9.9 MB 573.1 kB/s eta 0:00:04
   ------------------------------ --------- 7.6/9.9 MB 573.1 kB/s eta 0:00:04
   ------------------------------ --------- 7.6/9.9 MB 573.1 kB/s eta 0:00:04
   ------------------------------- -------- 7.9/9.9 MB 569.9 kB/s eta 0:00:04
   ------------------------------- -------- 7.9/9.9 MB 569.9 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/9.9 MB 567.6 kB/s eta 0:00:04
   -------------------------------- ------- 8.1/9.9 MB 567.6 kB/s eta 0:00:04
   ---------------------------------- ----- 8.4/9.9 MB 566.3 kB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.9 MB 566.3 kB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.9 MB 566.3 kB/s eta 0:00:03
   ----------------------------------- ---- 8.7/9.9 MB 563.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 587.2 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 587.2 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 595.3 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 603.2 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 607.0 kB/s  0:00:16
Downloading numpy-2.4.2-cp314-cp314-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 1.3 MB/s eta 0:00:10
   - -------------------------------------- 0.5/12.4 MB 1.3 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.4 MB 1.1 MB/s eta 0:00:11
   --- ------------------------------------ 1.0/12.4 MB 1.2 MB/s eta 0:00:10
   ---- ----------------------------------- 1.3/12.4 MB 1.1 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.4 MB 1.3 MB/s eta 0:00:09
   ------ --------------------------------- 2.1/12.4 MB 1.4 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/12.4 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.4 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.1/12.4 MB 1.5 MB/s eta 0:00:07
   ---------- ----------------------------- 3.4/12.4 MB 1.5 MB/s eta 0:00:07
   ------------ --------------------------- 3.9/12.4 MB 1.5 MB/s eta 0:00:06
   ------------- -------------------------- 4.2/12.4 MB 1.5 MB/s eta 0:00:06
   -------------- ------------------------- 4.5/12.4 MB 1.5 MB/s eta 0:00:06
   ---------------- ----------------------- 5.0/12.4 MB 1.5 MB/s eta 0:00:05
   ---------------- ----------------------- 5.2/12.4 MB 1.5 MB/s eta 0:00:05
   ----------------- ---------------------- 5.5/12.4 MB 1.5 MB/s eta 0:00:05
   ------------------- -------------------- 6.0/12.4 MB 1.5 MB/s eta 0:00:05
   -------------------- ------------------- 6.3/12.4 MB 1.5 MB/s eta 0:00:04
   --------------------- ------------------ 6.8/12.4 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 7.1/12.4 MB 1.6 MB/s eta 0:00:04
   ----------------------- ---------------- 7.3/12.4 MB 1.6 MB/s eta 0:00:04
   ------------------------ --------------- 7.6/12.4 MB 1.6 MB/s eta 0:00:04
   ------------------------- -------------- 7.9/12.4 MB 1.6 MB/s eta 0:00:03
   -------------------------- ------------- 8.1/12.4 MB 1.6 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.4 MB 1.6 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.4 MB 1.6 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.4 MB 1.6 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.4 MB 1.6 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.4 MB 1.6 MB/s eta 0:00:03
   ---------------------------- ----------- 8.9/12.4 MB 1.4 MB/s eta 0:00:03
   ----------------------------- ---------- 9.2/12.4 MB 1.4 MB/s eta 0:00:03
   ----------------------------- ---------- 9.2/12.4 MB 1.4 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.4 MB 1.3 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.4 MB 1.3 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.4 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 9.7/12.4 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 9.7/12.4 MB 1.3 MB/s eta 0:00:03
   ------------------------------- -------- 9.7/12.4 MB 1.3 MB/s eta 0:00:03
   -------------------------------- ------- 10.0/12.4 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 10.0/12.4 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 10.2/12.4 MB 1.2 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.2 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 1.2 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.4 MB 1.1 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.4 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.4 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.4 MB 1.1 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.4 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 11.0/12.4 MB 1.1 MB/s eta 0:00:02
   ----------------------------------- ---- 11.0/12.4 MB 1.1 MB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.4 MB 1.0 MB/s eta 0:00:02
   ------------------------------------ --- 11.3/12.4 MB 1.0 MB/s eta 0:00:02
   ------------------------------------- -- 11.5/12.4 MB 1.0 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.4 MB 1.0 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 1.0 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 1.0 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 992.6 kB/s  0:00:12
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [3]:
ecom = pd.read_csv('ecommerce_purchase.csv')

In [4]:

ecom.head()

,OrderID,CustomerID,CustomerName,Email,Product,Category,Quantity,Price,PaymentMethod,PurchaseDate,Country
0,1001,C001,John Smith,john.smith@email.com,Wireless Mouse,Electronics,2,25.99,Credit Card,2024-01-05,USA
1,1002,C002,Sarah Johnson,sarah.j@email.com,Running Shoes,Fashion,1,79.99,PayPal,2024-01-06,Canada
2,1003,C003,Michael Brown,michael.b@email.com,Bluetooth Speaker,Electronics,1,49.99,Debit Card,2024-01-07,UK
3,1004,C004,Emily Davis,emily.d@email.com,Coffee Maker,Home Appliances,1,89.99,Credit Card,2024-01-08,Australia
4,1005,C005,David Wilson,david.w@email.com,Desk Chair,Furniture,1,129.99,Net Banking,2024-01-09,USA

In [5]:
ecom.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        15 non-null     int64
 1   CustomerID     15 non-null     str
 2   CustomerName   15 non-null     str
 3   Email          15 non-null     str
 4   Product        15 non-null     str
 5   Category       15 non-null     str
 6   Quantity       15 non-null     int64
 7   Price          15 non-null     float64
 8   PaymentMethod  15 non-null     str
 9   PurchaseDate   15 non-null     str
 10  Country        15 non-null     str
dtypes: float64(1), int64(2), str(8)
memory usage: 1.4 KB

In [6]:
ecom.head(2)

,OrderID,CustomerID,CustomerName,Email,Product,Category,Quantity,Price,PaymentMethod,PurchaseDate,Country
0,1001,C001,John Smith,john.smith@email.com,Wireless Mouse,Electronics,2,25.99,Credit Card,2024-01-05,USA
1,1002,C002,Sarah Johnson,sarah.j@email.com,Running Shoes,Fashion,1,79.99,PayPal,2024-01-06,Canada

In [7]:
ecom['Price'].mean()
#mean() used for show average values

np.float64(212.72333333333324)

In [8]:

ecom['Price'].max()

np.float64(999.99)

In [9]:
ecom['Price'].min()

np.float64(4.99)

In [11]:
ecom[ecom['Category']=='Fashion'].count()
#sal['JobTitle'].value_counts().head()

OrderID          2
CustomerID       2
CustomerName     2
Email            2
Product          2
Category         2
Quantity         2
Price            2
PaymentMethod    2
PurchaseDate     2
Country          2
dtype: int64

In [12]:
ecom.head(1)

,OrderID,CustomerID,CustomerName,Email,Product,Category,Quantity,Price,PaymentMethod,PurchaseDate,Country
0,1001,C001,John Smith,john.smith@email.com,Wireless Mouse,Electronics,2,25.99,Credit Card,2024-01-05,USA

In [14]:
ecom[ecom['PaymentMethod'].str.contains("Credit Card")]['PaymentMethod'].count()

np.int64(6)

In [16]:

ecom['Category'].value_counts().head()

Category
Electronics        6
Fashion            2
Home Appliances    2
Furniture          2
Accessories        2
Name: count, dtype: int64

In [15]:
ecom['PaymentMethod'].value_counts().head()

PaymentMethod
Credit Card    6
PayPal         3
Debit Card     3
Net Banking    1
UPI            1
Name: count, dtype: int64

In [28]:
ecom.head(1)

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\r\nAlexisborough, NE ...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14

In [19]:
ecom[ecom['Product'] == 'Laptop']['Price']
# ecom[ecom['Country'] == 'USA']['CustomerName']

8    999.99
Name: Price, dtype: float64

In [22]:
ecom[ecom['CustomerID']=='C005']['Email']

4    david.w@email.com
Name: Email, dtype: str

In [24]:
ecom[(ecom['Product']=='Wireless Mouse') & (ecom['Price'] > 5)].count()

OrderID          1
CustomerID       1
CustomerName     1
Email            1
Product          1
Category         1
Quantity         1
Price            1
PaymentMethod    1
PurchaseDate     1
Country          1
dtype: int64

In [25]:
ecom[ecom['Country'].str.contains("USA")]['Country'].count() #Using str.contains to find the /25 year

np.int64(4)

In [26]:
#ecom['Email Domain'] = ecom['Email'].str.split("@").str[1] #Generate another column with email dominas using str split at the @ element, we keep the domain only
ecom['Email'].str.split("@").str[1]

0     email.com
1     email.com
2     email.com
3     email.com
4     email.com
5     email.com
6     email.com
7     email.com
8     email.com
9     email.com
10    email.com
11    email.com
12    email.com
13    email.com
14    email.com
Name: Email, dtype: object

In [27]:

ecom.head(1)

,OrderID,CustomerID,CustomerName,Email,Product,Category,Quantity,Price,PaymentMethod,PurchaseDate,Country
0,1001,C001,John Smith,john.smith@email.com,Wireless Mouse,Electronics,2,25.99,Credit Card,2024-01-05,USA

In [29]:
ecom['Email'].value_counts().head()
#ecom['Job'].value_counts().head()

Email
john.smith@email.com    1
sarah.j@email.com       1
michael.b@email.com     1
emily.d@email.com       1
david.w@email.com       1
Name: count, dtype: int64